name: WaluMetin
version: '${version}'
main: dev.walu.metin.WaluMetin
api-version: '1.20'
author: Walu
description: Metin Taşı eklentisi
softdepend: [PlaceholderAPI, DecentHolograms, HolographicDisplays, CMI]
commands:
  metintas:
    description: WaluMetin ana komut
    usage: /<command> [reload|admin|gui|olustur|sil|info]
    aliases: [metin, walumetin]
permissions:
  walumetin.admin:
    description: Reload, admin menu, stone creation and deletion
    default: op
    children:
      walumetin.gui: true
  walumetin.gui:
    description: Stone control panel access
    default: op
